keys:
  - &interloper age1nhsjw9ju9ezqpvre23exxjmhhzhz688t682dy2s28z7avsevr4dqhjpqfd
  - &stormveil age1pen3t2pauvtvpnce7k8pee68mhwyk8qawrsfktje88aq3zjrm4rq0kns6m
  - &server_ainsel age1r4mlnu2xcppdta73z77zpa3vwpgtdwueqcqf44mv5dqcsy6auvks2jw80r
  - &server_firelink age1zgx808cx5wtq50uk9xqwn2sse5muvg0snat5ywact0zcrvzr758q7xq7lk
  - &server_interloper age1q94wq7mhcnws7cf5wp6dauqdwjufyy6zjxv68na9s5sa78glkdnshu2hsm
  - &server_leyndell age1slmqtvvf2y4e2f5hkzry7ue0utgngpj9jeua93xntmwez7r7pc6qmth53a
  - &server_morne age18nfrzjrk7a3m2j4gx40zh8tvk0vk7c95ud23fckah938yd3xjatscvvzue
  - &server_nihilanth age17ckwdjgm2pnygszdxa7mmhdnafe8x8wq7k9g2d3ent4vasua2dsqfu2m76
  - &server_stormveil age1w0wpr80ta2ujm9rcd6tphjtvcn6sx25pnrky7q0lzyu4l7yfd4ps4wsk7e
creation_rules:
  - path_regex: secrets/common/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_ainsel
      - *server_firelink
      - *server_interloper
      - *server_leyndell
      - *server_morne
      - *server_nihilanth
      - *server_stormveil
  - path_regex: secrets/ainsel/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_ainsel
  - path_regex: secrets/firelink/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_firelink
  - path_regex: secrets/leyndell/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_leyndell
  - path_regex: secrets/morne/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_morne
  - path_regex: secrets/stormveil/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_stormveil
    