keys:
  - &interloper age1nhsjw9ju9ezqpvre23exxjmhhzhz688t682dy2s28z7avsevr4dqhjpqfd
  - &server_firelink age1zgx808cx5wtq50uk9xqwn2sse5muvg0snat5ywact0zcrvzr758q7xq7lk
  - &server_stormveil age1w0wpr80ta2ujm9rcd6tphjtvcn6sx25pnrky7q0lzyu4l7yfd4ps4wsk7e
creation_rules:
  - path_regex: secrets/firelink/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *server_firelink
  - path_regex: secrets/stormveil/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *server_stormveil
    