keys:
  - &interloper age1nhsjw9ju9ezqpvre23exxjmhhzhz688t682dy2s28z7avsevr4dqhjpqfd
  - &stormveil age1pen3t2pauvtvpnce7k8pee68mhwyk8qawrsfktje88aq3zjrm4rq0kns6m
  - &server_firelink age1zgx808cx5wtq50uk9xqwn2sse5muvg0snat5ywact0zcrvzr758q7xq7lk
  - &server_interloper age1q94wq7mhcnws7cf5wp6dauqdwjufyy6zjxv68na9s5sa78glkdnshu2hsm
  - &server_morne age18nfrzjrk7a3m2j4gx40zh8tvk0vk7c95ud23fckah938yd3xjatscvvzue
  - &server_staging age1857cwze56rhdymyqxevk302y73kcky7j54rcgy3htkklxn9a2fxqzmmu2m
  - &server_stormveil age1w0wpr80ta2ujm9rcd6tphjtvcn6sx25pnrky7q0lzyu4l7yfd4ps4wsk7e
creation_rules:
  - path_regex: secrets/common/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_firelink
      - *server_interloper
      - *server_morne
      - *server_staging
      - *server_stormveil
  - path_regex: secrets/firelink/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_firelink
  - path_regex: secrets/morne/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_morne
  - path_regex: secrets/staging/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_staging  
  - path_regex: secrets/stormveil/[^/]+\.yaml$
    key_groups:
    - age:
      - *interloper
      - *stormveil
      - *server_stormveil
    